### ISSUE TITLE
Problem with Spring module 1.3.7, anypoint studio Version: 7.14.0, mule 4

### ISSUE THREAD

**Issue by ValerioJiang** [mulesoft/docs-connectors#2205] opened 2023-01-12 11:17 UTC
Hello i tried to upgrade spring module from 1.3.6 to 1.3.7 but kept giving me error within the xml file, i report here the log
`[INFO] About to fetch required dependencies for artifact: 3e862200-926a-11ed-8785-0050568c761c:3e862200-926a-11ed-8785-0050568c761c:pom:4.5.0-20220622. This may take a while...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.900 s
[INFO] Finished at: 2023-01-12T12:14:14+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.mule.tools.maven:mule-maven-plugin:3.8.0:process-classes (default-process-classes) on project es1: Execution default-process-classes of goal org.mule.tools.maven:mule-maven-plugin:3.8.0:process-classes failed: There was '1' error while parsing the given file 'es1.xml'.
[ERROR] Full list:
[ERROR] org.xml.sax.SAXParseException; lineNumber: 18; columnNumber: 40; cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.mulesoft.org/schema/mule/spring":delegate-security-providers}'. One of '{"http://www.mulesoft.org/schema/mule/core":annotations, "http://www.mulesoft.org/schema/mule/spring":delegate-security-provider}' is expected.
[ERROR] -> [Help 1]
[ERROR] `

I tried to correct namespace in the xml and checked all the dependecies in the pom, but they're all ok,
if i rollback to version 1.3.6 everything will run again, i think there is some conflict within the xsi location in the xml file, hope to not saying bs.

**Comment by valkyrie69** [comment] 2023-05-04 17:43
@kevintroller Can you check with dev about this issue?

**Comment by kevintroller** [comment] 2023-05-04 18:23
I confirmed with the Connectivity developer team that issue is already being investigated by multiple MuleSoft developer teams as they are trying to find the cause of why the XML recreates an additional tag. Closing this issue in our docs-connector repository as it's not a Docs issue

**Closed as completed by kevintroller** 2023-05-04 18:23 UTC
